from typing import List

from dotenv import load_dotenv
from pydantic import BaseModel, Field

load_dotenv()
from langchain.agents import create_agent
from langchain_core.messages import HumanMessage
from langchain_ollama import ChatOllama
from langchain_openai import ChatOpenAI
from langchain_tavily import TavilySearch

# tavily = TavilyClient()


class source(BaseModel):
    """schema for source used by the agent"""

    url: str = Field(description="The URL of the source")


class AgentResponse(BaseModel):
    """Schema for the agent response"""

    answer: str = Field(description="The answer generated by the agent")
    sources: List[source] = Field(
        default_factory=List,
        description="The list of sources used to generate the answer",
    )


# @tool()
# def search_web(query: str) -> dict:
#     """Get the current weather in a given location"""
#     # For demonstration purposes, we'll return a static response.
#     print(f"searching for {query=}")
#     return tavily.search(query=query)

llm = ChatOpenAI(model="gpt-4o", temperature=0)
tools = [TavilySearch()]
agent = create_agent(llm, tools, response_format=AgentResponse)


def main():
    print("this is main")
    result = agent.invoke(
        {
            "messages": HumanMessage(
                content="search for 3 job postings for an AI engineer using langchain in India on LinkedIn"
            )
        }
    )
    print(result)


if __name__ == "__main__":
    main()
